<!文档类型 html>
<html 郎=“恩">
  <头>
    <元字符集=“UTF-8" />
    <元内容=“X-UA兼容”内容=“IE=边缘" />
    <元名称=“视口”内容=“宽度=设备宽度，初始比例=1.0" />
    <标题>未来空间</标题>
    <链接 rel=“样式表” href=“./css/bootstrap.min.css" />
    <链接 rel=“样式表” href=“./css/base.css" />
    <链接 rel=“样式表” href=“./css/main.css" />
  </头>
  <身体>
    <除法 id=“粒子-js”></除数>

    <标头 id=“标头">
      <导航 id=“导航">
        <a href=“#welcome”>欢迎</a>
        <a href=“#token规划”>标记规划</a>
        <a 赫里夫=“#origin”>起源</a>
        <a href=“#introduction”>简介</a>
        <a href=“#our计划”>我们的计划</a>
        <a href=“#team-contact”>团队联系方式</a>
      </导航>
    </页眉>

    <部分 id=“欢迎">
      <div 类 =“container">
        <div 类 =“行对齐-项-居中">
          <div 类 =“col-lg-6 col-md-12 col-sm-12 顺序-lg-第一文本-lg-左文本-居中">
            <h1 类=“标题”>未来空间</h1>
            <h5 类=“内容">
“在实现我毕生梦想的过程中，我意识到指挥这个梦想的重大责任。
任务。历史性的太空之旅正在等待着我们，但希望这次任务能够增强启蒙，
带我们走得更远，在地球上取得非凡的成就。
            </h5>
            <div 类 =“联系 d-flex 对齐-内容-中心对齐-内容-lg-开始对齐-项目-中心">
              <a href=“https://t.me/Future_Space” 目标=“_blank">
                <img src=“./图像/icon_telegram.png” 类=“图标电报" />
                <跨>电报</跨度>
              </一个>
              <a href=“https://twitter.com/Futurespace_BSC?s=09” 目标=“_blank">
                <img src=“./图像/icon_twitter.png” 类=“图标推特" />
                <跨度>推特</跨度>
              </一个>
              <a href=“./白皮书.pdf” 目标=“_blank">
                <跨度>白纸</跨度>
              </一个>
            </迪夫>
          </迪夫>
          <div 类 =“col-lg-6 col-md-12 col-sm-12 顺序-优先">
            <img src=“./图像/astronaut_fly.png” 类=“图像" />
            <!-- <图像线“/图像/astronaut_fly_line.png”类=“图像线” /> -->
          </迪夫>
        </迪夫>
      </迪夫>
    </部分>
    <部分 id=“令牌规划">
      <div 类 =“container">
        <div 类 =“行对齐-项-居中">
          <div 类 =“col-lg-6 col-md-12 col-sm-12">
            <h1 类=“标题”>标记计划</h1>
            <h5 类=“内容">
太空旅游是基于人们在太空中旅行的理想。在太空中旅行提供了
前所未有的体验。最新颖、最令人兴奋的是欣赏太空的美丽风景和
失重的味道。这两种体验只能在太空中享受。可以说，这
场景只能在天空中欣赏。
            </h5>
          </迪夫>
          <div 类 =“col-lg-6 col-md-12 col-sm-12">
            <img src=“./图像/token_planning.png” 类=“图像" />
          </迪夫>
        </迪夫>
      </迪夫>
    </部分>
    <部分 id=“原点">
      <div 类 =“container">
        <div 类 =“行对齐-项-居中">
          <div 类 =“col-lg-5 col-md-12 col-sm-12">
            <img src=“./图像/astronaut_lie.png” 类=“图像" />
          </迪夫>
          <div 类 =“col-lg-7 col-md-12 col-sm-12">
            <h1 类=“标题”>起源</h1>
            <h5 类=“内容">
未来空间的创始团队来自欧洲航空集团。此令牌基于高级
由BEP2.0开发的模因令牌。我们拥有强大的技术团队，完善的市场价值管理，以及
足够的财政支持。我们一定会把这个令牌带到月球上，这样世界就会
认识到未来空间的重要性。
            </h5>
          </迪夫>
        </迪夫>
      </迪夫>
    </部分>
    <部分 id=“简介">
      <div 类 =“container">
        <div 类 =“行对齐项结束">
          <div 类 =“col-lg-8 col-md-12 col-sm-12">
            <h1 类=“标题文本中心”>简介</h1>
            <h5 类=“内容">
未来空间的开发者在原有BEP的基础上进行了创新，这意味着它不是
只是一个象征，也代表着未来宇航员的每一个身份。在浩瀚的太空中，每一个
航空科学家努力坚持自己对未来发展的立场
国家。未来空间的诞生将是空间的主要风力目标，也是未来的第一个愿景
太空在未来，让每一位宇航员进入他梦想中的宇宙。
            </h5>
          </迪夫>
          <div 类 =“col-lg-4 col-md-12 col-sm-12 d-flex 对齐-内容-中心对齐-内容-lg-端">
            <div 类 =“图像框">
              <img src=“./图像/astronaut_fishing.png” 类=“图像" />
            </迪夫>
          </迪夫>
        </迪夫>
      </迪夫>
    </部分>
    <部分 id=“我们的计划">
      <div 类 =“container">
        <div 类 =“标头 d-flex 对齐-内容-周围对齐-项目-居中">
          <h1 类=“标题”>我们的计划</h1>
          <img src=“./图像/astronaut_candy.png” 类=“图像" />
        </迪夫>
        <h5 类=“内容">
未来空间创石团队承诺完全透明。如果用户在任何
过程中，欢迎及时投诉。然后我们将奖励10000美元作为奖励和
同时销毁所有令牌
        </h5>
      </迪夫>
    </部分>
    <部分 id=“团队联系人">
      <img src=“./图像/团队.png” 类=“图像" />
      <div 类 =“联系 d-flex 对齐-内容-中心对齐-项目-中心">
        <一个
          href=“https://t.me/Future_Space"
          目标=“_blank"
          class=“d-内联-弯曲对齐-内容-中心对齐-项目-中心"
        >
          <img src=“./图像/icon_telegram.png” 类=“图标电报" />
          <跨>电报</跨度>
        </一个>
        <一个
          href=“https://twitter.com/Futurespace_BSC?s=09"
          目标=“_blank"
          class=“d-内联-弯曲对齐-内容-中心对齐-项目-中心"
        >
          <img src=“./图像/icon_twitter.png” 类=“图标推特" />
          <跨度>推特</跨度>
        </一个>
      </迪夫>
    </部分>

    <脚本 src=“./js/粒子.js”></脚本>
    <script src=“./js/jquery.min.js”></script>
    <脚本 src=“./js/main.js”></脚本>
  </身体>
</网页>
